version: '3'

services:
  api:
    restart: always
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    entrypoint:
      - ./startapp.sh
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authorshaven
  